# development:
#   dialect: mysql
#   datasource: ${DB_USER}:${DB_PASS}@tcp(${DB_HOST}:${DB_PORT})/${DB_NAME}?parseTime=true
#   dir: migration/
development:
  dialect: sqlite3
  datasource: test.db
  dir: migration/sqlite3
